version: '2.1'
orbs:
  newman: postman/newman@1.0.0
jobs:
  build:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./Proxima_AI_Quiz.postman_collection.json
          environment: ./proxima_ai_quiz_env.postman_environment.json
workflows: null